"""
platform: win
env: any
name: analyze_ecif.py
analyze model generated by ecif::gbt and ecif::autogluon
"""
import os

import pandas as pd
import numpy as np
from config import *
from DatasetMng.IndexMng import get_index_from_dir
import matplotlib.pyplot as plt
import pickle
from sklearn.metrics import r2_score, mean_squared_error
import time

affinity_data = pd.read_csv('../Preprocess/BindingData.csv', comment='#')
ecif_data = pd.read_csv(os.path.join(ecif_data_dir, 'ECIF_6.0.csv'), comment='#')
ld_data = pd.read_csv(os.path.join(ecif_data_dir, 'RDKit_Descriptors.csv'), comment='#')


def query_pk_by_id(qid):
    """
    get the pk value by query id
    :param qid: query id
    :return: pk value
    """
    return float(affinity_data[affinity_data['PDB'] == qid]['pK'])


def query_described_value(qid):
    """
    get the descriptor values by query id
    :param qid: query id
    :return: descriptor value
    """
    ecif_cut = ecif_data[ecif_data['PDB'] == qid].iloc[:, 1:]
    ld_cut = ld_data[ld_data['PDB'] == qid].iloc[:, 1:]
    return ecif_cut.join(ld_cut)


def predict_on_core(d):
    """
    predict gbt model on core set
    :param d: cutoff distance, default: 6.0
    :return: statistic plot
    """
    core_ids = get_index_from_dir(ecif_core)
    actual = []
    predicted = []
    model = pickle.load(open(os.path.join(ecif_model_dir, 'ecif_gbt_{}.pkl'.format(d)), 'rb'))
    for id in core_ids:
        actual.append(query_pk_by_id(id))
        predicted.append(model.predict(query_described_value(id))[0])
    plt.title(label='ECIF::GBT')
    plt.scatter(actual, predicted, color="orange")
    # plt.plot([actual.min(), actual.max()], [predicted.min(), predicted.max()], 'r--', lw=2)
    plt.xlabel('actual')
    plt.ylabel('predicted')
    plt.xlim(0.0, 16.0)
    plt.ylim(0.0, 16.0)
    line_param = np.polyfit(actual, predicted, deg=1)
    y = [i*line_param[0]+line_param[1] for i in actual]
    plt.plot(actual, y, color="red")
    rmse = mean_squared_error(actual, predicted) ** 0.5
    r = r2_score(actual, predicted) ** 0.5
    plt.text(2, 14, 'rmse: {}'.format(rmse))
    plt.text(2, 12, 'r: {}'.format(r))

    plt.show()


def predict_on_core_ag(model):
    """
    predict autogluon model on core set
    :param model: specific model generated by autogluon
    :return: statistic plot
    """
    core_ids = get_index_from_dir(ecif_core)
    actual = []
    predicted = []
    model = pickle.load(open(model, 'rb'))
    for id in core_ids:
        actual.append(query_pk_by_id(id))
        predicted.append(model.predict(query_described_value(id))[0])
    plt.title(label='ECIF::Autogluon')
    plt.scatter(actual, predicted, color="orange")
    # plt.plot([actual.min(), actual.max()], [predicted.min(), predicted.max()], 'r--', lw=2)
    plt.xlabel('actual')
    plt.ylabel('predicted')
    plt.xlim(0.0, 16.0)
    plt.ylim(0.0, 16.0)
    line_param = np.polyfit(actual, predicted, deg=1)
    y = [i * line_param[0] + line_param[1] for i in actual]
    plt.plot(actual, y, color="red")
    rmse = mean_squared_error(actual, predicted) ** 0.5
    r = r2_score(actual, predicted) ** 0.5
    plt.text(2, 14, 'rmse: {}'.format(rmse))
    plt.text(2, 12, 'r: {}'.format(r))

    plt.show()


def predict_ex(f_pro, f_lig, d):
    """
    predict on protein-ligand pairs not in core set
    :param f_pro: protein file, .pdb
    :param f_lig: ligand file, .sdf
    :param d: cutoff distance, default 6.0
    :return: prediction
    """
    from util.ECIF import ECIF
    ecif_helper = ECIF(2016)
    ecif = ecif_helper.get_ecif(f_pro, f_lig, float(d))
    ld = ecif_helper.get_ligand_features_by_file(f_lig)
    model = pickle.load(open(os.path.join(ecif_model_dir, 'ecif_gbt_{}.pkl'.format(d)), 'rb'))
    data = ecif + list(ld)
    cols = ecif_helper.get_possible_ecif() + ecif_helper.get_ligand_descriptors()
    data_f = pd.DataFrame([data], columns=cols)
    return model.predict(data_f)[0]


def predict_ex_ag(f_pro, f_lig, model):
    """
    predict on protein-ligand pairs not in core set
    :param f_pro: protein file, .pdb
    :param f_lig: ligand file, .sdf
    :param model: specific model generated by autogluon
    :return: prediction
    """
    from util.ECIF import ECIF
    ecif_helper = ECIF(2016)
    ecif = ecif_helper.get_ecif(f_pro, f_lig, float(6.0))
    ld = ecif_helper.get_ligand_features_by_file(f_lig)
    m = pickle.load(open(model, 'rb'))
    data = ecif + list(ld)
    cols = ecif_helper.get_possible_ecif() + ecif_helper.get_ligand_descriptors()
    data_f = pd.DataFrame([data], columns=cols)
    return m.predict(data_f)[0]


def my_test():
    """
    test
    :return:
    """
    predict_on_core('6.0')
    predict_on_core_ag(ecif_example)


def estim_ext(ids, d):
    """
    for extra tests, do estimations on a list of proteins that are belongs to PDBBind dataset
    :param ids: indexes of proteins
    :param d: cutoff distance, default 6.0
    :return: predictions
    """
    actual = []
    predicted = []
    model = pickle.load(open(os.path.join(ecif_model_dir, 'ecif_gbt_{}.pkl'.format(d)), 'rb'))
    for id in ids:
        actual.append(query_pk_by_id(id))
        predicted.append(model.predict(query_described_value(id))[0])
    print("\n")
    print("pred:")
    print(predicted)
    print("actual:")
    print(actual)


def estim_not_ext(test_name):
    """
    for extra tests, do estimations on a list of proteins that are not belongs to PDBBind dataset;
    different from estim_ext(), actual values should be found personally
    :param test_name: the test folder in which list of proteins can be found
    :return: predictions
    """
    print("\n")
    ids = os.listdir(os.path.join(test_dir, test_name))
    preds = []
    preds_ag = []
    for i in ids:
        f_prot = os.path.join(test_dir, test_name, "{}\\{}_protein.pdb".format(i, i))
        f_ligd = os.path.join(test_dir, test_name, "{}\\{}_ligand.sdf".format(i, i))
        # pk = predict_ex(f_prot, f_ligd, '6.0')
        # preds.append(pk)
        pk_ag = predict_ex_ag(f_prot, f_ligd, ecif_example)
        preds_ag.append(pk_ag)

    print("\n")
    result = pd.DataFrame(preds_ag, ids, columns=["GBT"])
    # result = pd.DataFrame(preds, ids, columns=["GBT"]).join(
    #     pd.DataFrame(preds_ag, ids, columns=["AG"])
    # )

    print(result)
    # result.to_csv(r"D:\AlexYu\PAFF\tests\20220706\result.csv")


if __name__ == '__main__':
    # estim_not_ext("20220706")
    # my_test()
    # estim_ext(['4djv', '4djy', '4djw', '4djx'], 6.0)
    # estim_ext(['4gmy', '4gj2', '4hw2', '4hw3'], 6.0)
    # estim_ext(['2zc9', '1h1s'], 6.0)
    start = time.perf_counter()
    estim_not_ext("20220711")
    end = time.perf_counter()
    print("\nTime: {}\n".format(round(end - start)))
    # estim_not_ext("20220719")

